### ISSUE TITLE
[Bug] [Unexpected Error] -> RuntimeError -> This portal is not running

### ISSUE THREAD

**Issue by panpan0818** [OpenBB-finance/OpenBB#6959] opened 2024-11-22 04:14 UTC
**Describe the bug**
Openbb successful installed but when I run the following code in vscode enviorment:

 from openbb import obb
obb.equity.search("JPMorgan", provider="nasdaq").to_df().head(3)

it show error:
Traceback (most recent call last):
  File "d:\Desktop\Stock Price\test_openbb.py", line 3, in <module>
    obb.equity.search("JPMorgan", provider="nasdaq").to_df().head(3)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\panpan0818\AppData\Roaming\Python\Python311\site-packages\openbb_core\app\static\utils\decorators.py", line 100, in wrapper
    raise OpenBBError(
  File "D:\Anaconda\Lib\site-packages\anyio\from_thread.py", line 148, in _check_running
    raise RuntimeError('This portal is not running')
openbb_core.app.model.abstract.error.OpenBBError:
[Unexpected Error] -> RuntimeError -> This portal is not running

I have already uninstalled this library and again installed it, also tried installing ipykernel and anyio library but it still not working.

**Comment by deeleeramone** [comment] 2024-11-22 21:18
Hi there, this is not a bug. You have a bad environment, looks like there is not even one to begin with. Always use virtual environments.

`anyio` should not be getting called from a path that is different than your environment.

You have installed OpenBB to your system Python installation, and you have Anaconda installed in your $PATH that is using modules that it shouldn't be.

Closing this issue because it's not a bug.

**Closed by deeleeramone** 2024-11-22 21:18 UTC
