### ISSUE TITLE
[Bug] what decide the defaulted provider of endpoint

### ISSUE THREAD

**Issue by joshuaBri** [OpenBB-finance/OpenBB#6971] opened 2024-11-28 01:37 UTC
![56005c4c-eaad-4315-a11c-ed3c84329151](https://github.com/user-attachments/assets/56ed431d-eb49-421e-9cd2-6c6b11f37724)

Such as this endpoint,once you click the "try it out",there will be one default provider. Which part of code decide it?
I am desperate to know it. Thanks.

**Comment by deeleeramone** [comment] 2024-11-28 02:46
This is part of `user_settings.json` - https://docs.openbb.co/platform/user_guides/settings_and_environment_variables#defaults

Closing because this is not a bug.

**Closed by deeleeramone** 2024-11-28 02:46 UTC

**Comment by joshuaBri** [comment] 2024-11-28 03:31
Sorry to bother your time, But it won't work in the CI docx.
![image](https://github.com/user-attachments/assets/8290c29e-5fe9-4697-9d83-835a476a7ff8)
![image](https://github.com/user-attachments/assets/2f87a837-7a58-4280-bdc5-34d437757297)
The defaulted provider is fred still.

**Comment by joshuaBri** [comment] 2024-11-28 03:33
> This is part of `user_settings.json` - https://docs.openbb.co/platform/user_guides/settings_and_environment_variables#defaults
> 
> Closing because this is not a bug.

The settings can't change CI docx.
