### ISSUE TITLE
Incorrect Currency Symbol for NSE-Listed Stocks

### ISSUE THREAD

**Issue by harshsinha-12** [OpenBB-finance/OpenBB#6845] opened 2024-10-22 19:19 UTC
**Description:**
It is related to currency conversion for stocks. The Stocks listed in India (on NSE) with the ticker of the form (e.g., RELIANCE.NS) display the current value in INR, but the symbol shown is “$.” Meanwhile, the financial figures appear in Cr. INR only.

**Expected Behavior:**
The currency symbol should match the currency of the price displayed. For example, if the stock price is in INR, the symbol should be “₹” instead of “$.”

**To Reproduce:**
	1.	Go to https://pro.openbb.co/app/data-connectors.
	2.	Navigate to My Dashboards on the left.
	3.	Create a new dashboard by clicking the “+” icon.
	4.	Search for widgets.
	5.	Navigate to Equity from Categories.
	6.	Search for or select “Ticker Information.”
	7.	It might be AAPL by default. Please change it to RELIANCE.NS (Reliance Industries Limited).
	8.	The price shown is in INR (numerically) but the symbol used is in dollars.

**Screenshots**

<img width="822" alt="Screenshot 2024-10-23 at 12 38 11 AM" src="https://github.com/user-attachments/assets/3abc6749-1c23-4447-b980-700fe8adda8a">

**Desktop:**
	•	OS: MacOS Sequoia 15.0.1

**Additional Context:**
I have worked on a similar issue while building https://profitolio.streamlit.app/. The solution I used was to check for the ticker, and if it contains ‘.NS’, I would fetch the current USD/INR rates from yfinance and use them for conversion.

The solution here could be region-dependent. For example, someone using the website in the US should be able to check prices in USD after conversion, while users in India should see the stocks with ‘.NS’ in the ticker in INR only when the default currency is set to INR.

**Comment by LindaWang7** [comment] 2024-11-14 03:59
Maybe I take this issue?

**Comment by deeleeramone** [comment] 2024-11-19 00:29
Closing because the issue is not related to any code in this repo. @harshsinha-12, has been noted and next time please report bugs directly from the application, thanks.

**Closed by deeleeramone** 2024-11-19 00:29 UTC
Labels: bug, Terminal
