### ISSUE TITLE
[Bug] Unable to pull multiple earnings reports using for loop

### ISSUE THREAD

**Issue by kchander92** [OpenBB-finance/OpenBB#6239] opened 2024-03-20 07:01 UTC
I'm trying to write a for loop to pull cash statements for all the tickers in the NYSE. The for loop below contains a try-except block for when quarterly cash statements for a given ticker cannot be returned from Polygon from the last ten years:

```
cash_statements = {}

for ticker in nyse.symbol:
    try:
        cash_statements[ticker] = obb.equity.fundamental.cash(ticker, provider="polygon", limit=40, period='quarter').to_df()
    except:
        print('{} not available'.format(ticker))
```
A sample of the output is shown below, with the following tickers not having cash statements available as the for loop is executing:
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/101078824/e91db678-af0c-425f-8b32-c744a374a007)

Note that "JPM not available" is underlined. The quarterly cash statements from the last 10 years couldn't be pulled using the for loop. However, when I call the code below to pull JPM's cash statements, I do get an output:
`obb.equity.fundamental.cash('JPM', provider="polygon", limit=40, period='quarter').to_df()`
![image](https://github.com/OpenBB-finance/OpenBBTerminal/assets/101078824/26a3cadf-c0b7-4b8d-84b1-bb429b25fb8c)
(The dataframe has been truncated for the sake of brevity.)

Do you know what could be causing this inconsistency, for the stand-alone cash statement query to work for JPM but not when it's run in a for loop? Is there a better way you would recommend pulling the cash statements for multiple tickers? Thanks.

- OS: Windows 11
- Python version 3.11.8

**Comment by IgorWounds** [comment] 2024-03-20 10:01
Hello,

Can you check your Polygon API key privileges and make sure that you're not being rate-limited? 

I can't reproduce this on my end completely as I'm not sure what `nyse.symbol` looks like. Here is a dummy version that works for me:

```
cash_statements = {}
symbols = ["JPM", "XOM", "MA"]

for ticker in symbols:
    try:
        cash_statements[ticker] = obb.equity.fundamental.cash(ticker, provider="polygon", limit=40, period='quarter').to_df()
    except Exception as e:
        print(e)
```

**Comment by kchander92** [comment] 2024-03-21 06:22
It looks like the [free plan for Polygon](https://polygon.io/pricing) as the source allows 5 API calls per minute, so there does appear to be rate limiting going on.

**Comment by IgorWounds** [comment] 2024-03-21 09:24
Can you show me the full exception that is being thrown, please?

**Comment by deeleeramone** [comment] 2024-03-21 19:12
FYI, Polygon uses a period for share classes and not a "-". `BRK-A` = `BRK.A`

**Comment by deeleeramone** [comment] 2024-08-01 18:19
Closing because issue is access level from the provider.

**Closed by deeleeramone** 2024-08-01 18:19 UTC
