### ISSUE TITLE
[Bug] Charting Danish stocks from OMX Copenhagen fails

### ISSUE THREAD

**Issue by StryDK** [OpenBB-finance/OpenBB#6874] opened 2024-10-25 12:43 UTC
**Describe the bug**
Trying to show OMX Copenhagen tickers, eg. ROCK-A.CO (ROCKWOOL A/S) in the charting widget returns a symbol error (screenshot). Moreover, the currency symbol is wrong, should be DKK. See [https://github.com/OpenBB-finance/OpenBB/issues/6845](url)

**To Reproduce**
1. Create a new dashboard by clicking the “+” icon
2. Select Add Template
3. Select the Charting template
4. In the charting dashboard, push the blue "+" to add a widget
5. Add the Ticker information widget, and arrange them as in the screenshot, and make sure the two widgets are grouped
6. In the Ticker information widget, search for "ROCK-A.CO"

**Screenshots**
![image](https://github.com/user-attachments/assets/54b5ce8e-f7b9-411f-bdea-1d9e2d56e226)

**Desktop (please complete the following information):**

- OS: Windows 11 Home -  Version 10.0.22631 Build 22631

**Additional context**
I suspect that this issue stems from TradingView using different ticker symbols. In the case of ROCKWOOL A/S, the symbol is ROCK_A in TradingView [https://www.tradingview.com/chart/?symbol=OMXCOP%3AROCK_A](url) and ROCK-A.CO in OpenBB

**Comment by deeleeramone** [comment] 2024-10-25 16:53
Hello, and thanks for the report. This is a known issue that is being worked on, so hopefully a solution soon. 

For future reports, please report them from directly in the application. This repo is for the open source Platform code and does not host any of the web application elements.

**Comment by deeleeramone** [comment] 2024-11-19 00:30
Closing because the issue is not related to any code in this repo.

**Closed by deeleeramone** 2024-11-19 00:30 UTC
Labels: bug, Terminal
