### ISSUE TITLE
[Bug] Usage example files seems outdated

### ISSUE THREAD

**Issue by Manish-k723** [OpenBB-finance/OpenBB#6741] opened 2024-10-05 18:34 UTC
**Description**
I simple logged into openbb platform and went into notebook examples. I opened one of the file and directly tried to execute the file in google colab and guess what, it threw error. 
<--ModuleNotFoundError: no module named open bb-terminal-->

I even tried to run other notebooks and found the same problem with every notebook

**To Reproduce**
Open any one of the following files and try to run them in google colab.

https://github.com/OpenBB-finance/OpenBB/tree/develop/examples

**Screenshots**
<img width="913" alt="image" src="https://github.com/user-attachments/assets/5935d5bf-9204-48cf-935d-8371e1d90069">

**Additional context**
Even, I tried to read more about this thing openbb-terminal, I am not sure, how much I am wrong but didn't really found anything. helpful even with 3 hours of good research. Even using direct lines from openbb docs, resulting in same error. It would be great if someone from team help me out to understand this.

**Comment by deeleeramone** [comment] 2024-10-06 22:18
Hi, the items under "v3" are for the legacy code. You're right though, we are at a point now where these should be removed.

**Comment by deeleeramone** [comment] 2024-10-06 22:30
Closing because this is not a bug.

**Closed by deeleeramone** 2024-10-06 22:30 UTC
